"""Valuation service for computing program impact."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Mapping

from ..core.utils import clamp

ANOMALY_MULTIPLIER_RANGE = (0.05, 0.15)
FORECAST_MULTIPLIER_RANGE = (0.15, 0.25)

SYNERGY_MULTIPLIERS: Mapping[str, float] = {
    "mid": 1.3,
    "large": 1.7,
    "f500": 2.2,
}


@dataclass
class ValueInputs:
    """Normalized valuation inputs used by the calculator."""

    annual_spend: float
    anomaly_spend: float
    rightsizing_monthly_savings: float
    reservable_spend: float
    tier: str
    anomaly_count: int = 0


@dataclass
class ValueReport:
    """Structured valuation output used by APIs and tests."""

    anomaly: float
    rightsize: float
    forecast: float
    integrated: float
    assumptions: Dict[str, object]

    def to_dict(self) -> Dict[str, object]:
        """Return a JSON-serializable representation."""

        return {
            "anomaly": self.anomaly,
            "rightsize": self.rightsize,
            "forecast": self.forecast,
            "integrated": self.integrated,
            "assumptions": self.assumptions,
        }


def _anomaly_value(inputs: ValueInputs) -> float:
    """Return the annualized anomaly protection value."""

    affected = max(inputs.anomaly_spend, 0.0)
    if inputs.annual_spend <= 0:
        multiplier = ANOMALY_MULTIPLIER_RANGE[0]
    else:
        severity = clamp(affected / inputs.annual_spend, 0.0, 1.0)
        multiplier = ANOMALY_MULTIPLIER_RANGE[0] + (
            (ANOMALY_MULTIPLIER_RANGE[1] - ANOMALY_MULTIPLIER_RANGE[0]) * severity
        )
    if inputs.anomaly_count:
        multiplier = clamp(
            multiplier * (1.0 + min(inputs.anomaly_count / 100, 0.05)),
            0.0,
            ANOMALY_MULTIPLIER_RANGE[1],
        )
    return affected * multiplier


def _rightsize_value(inputs: ValueInputs) -> float:
    """Return annualized savings from right-sizing recommendations."""

    monthly = max(inputs.rightsizing_monthly_savings, 0.0)
    return monthly * 12


def _forecast_value(inputs: ValueInputs) -> float:
    """Return annualized value generated by reservation-friendly forecasts."""

    reservable = max(inputs.reservable_spend, 0.0)
    if inputs.annual_spend <= 0:
        multiplier = FORECAST_MULTIPLIER_RANGE[0]
    else:
        ratio = clamp(reservable / inputs.annual_spend, 0.0, 1.0)
        multiplier = FORECAST_MULTIPLIER_RANGE[0] + (
            (FORECAST_MULTIPLIER_RANGE[1] - FORECAST_MULTIPLIER_RANGE[0]) * ratio
        )
    return reservable * multiplier


def compute_value_report(inputs: ValueInputs) -> ValueReport:
    """Compute the valuation breakdown for the provided inputs."""

    anomaly_val = _anomaly_value(inputs)
    rightsize_val = _rightsize_value(inputs)
    forecast_val = _forecast_value(inputs)

    synergy = SYNERGY_MULTIPLIERS.get(inputs.tier.lower(), 1.0)
    integrated_val = (anomaly_val + rightsize_val + forecast_val) * synergy

    return ValueReport(
        anomaly=anomaly_val,
        rightsize=rightsize_val,
        forecast=forecast_val,
        integrated=integrated_val,
        assumptions={
            "anomaly_multiplier": ANOMALY_MULTIPLIER_RANGE,
            "forecast_multiplier": FORECAST_MULTIPLIER_RANGE,
            "tier_multiplier": synergy,
        },
    )


def estimate_value(metrics: Dict[str, float]) -> float:
    """Backwards-compatible helper for legacy callers."""

    params = ValueInputs(
        annual_spend=metrics.get("annual_spend", 0.0),
        anomaly_spend=metrics.get("anomaly_spend", 0.0),
        rightsizing_monthly_savings=metrics.get("rightsizing_monthly_savings", 0.0),
        reservable_spend=metrics.get("reservable_spend", 0.0),
        tier=str(metrics.get("tier", "mid")),
        anomaly_count=int(metrics.get("anomaly_count", 0)),
    )
    report = compute_value_report(params)
    return report.integrated
