[env:ttgo-t-beam]
platform = espressif32
board = ttgo-t-beam
framework = arduino
monitor_speed = 115200
lib_deps =
    arduino-libraries/ArduinoJson@^6.21.2
    rweather/Crypto@^0.4.0
    mcci-catena/MCCI LoRaWAN LMIC library@^4.1.1
    adafruit/Adafruit NeoPixel@^1.12.0
    sandeepmistry/LoRa@^0.8.0
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_RUNNING_CORE=1
    -DARDUINO_EVENT_RUNNING_CORE=1
